# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@multiformats/base-x-4.0.1" = {
      name = "_at_multiformats_slash_base-x";
      packageName = "@multiformats/base-x";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@multiformats/base-x/-/base-x-4.0.1.tgz";
        sha512 = "eMk0b9ReBbV23xXU693TAIrLyeO5iTgBZGSJfpqriG8UkYvr/hC9u9pyMlAakDNHWmbhMZCDs6KQO0jzKD8OTw==";
      };
    };
  };
  args = {
    name = "beep-client";
    packageName = "beep-client";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@multiformats/base-x-4.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = ".... . .-.. .-.. --- / .-- --- .-. .-.. -..";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
